#!/bin/sh
#
# Workaround for multistrap bug #688628.
#

set -e

wkdir=

menage() {
  [ -z "$wkdir" ] || rm -fr "$wkdir"
}

trap 'menage' EXIT INT ABRT KILL TERM

wkdir=$(mktemp -d)
cd "$wkdir"

cat <<EOF >fix.sh
#!/bin/sh
echo \$CROSSVERS
sed -i 's/\[.*\] //' /etc/apt/sources.list.d/multistrap-debian.list
sed -i 's/cdn\.debian\.net/ftp2.fr.debian.org/' /etc/apt/sources.list.d/multistrap-debian.list
cat /etc/apt/sources.list.d/multistrap-debian.list
# Fix for missing default cross-gcc
# See <http://lists.debian.org/debian-embedded/2012/09/msg00066.html>
eval "\$(dpkg-architecture -a\$CROSSARCH)"
if [ -z "\$DEB_HOST_MULTIARCH" ]; then
  DEB_HOST_MULTIARCH=\$DEB_HOST_GNU_TYPE
fi
if [ ! -x /usr/bin/\$DEB_HOST_MULTIARCH-gcc ]; then
  exes="gcc gcov g++ cpp gcc-nm gcc-ar gcc-ranlib"
  for exe in \$exes; do
    if [ -x /usr/bin/\$DEB_HOST_MULTIARCH-\$exe-\$CROSSVERS ]; then
      ln -s \$DEB_HOST_MULTIARCH-\$exe-\$CROSSVERS /usr/bin/\$DEB_HOST_MULTIARCH-\$exe
    fi
  done
fi
ls -l /usr/bin/\$DEB_HOST_MULTIARCH-*
EOF
chmod a+x fix.sh

if [ "$DIST" != squeeze ]; then
  echo "dpkg --add-architecture $CROSSARCH" >>fix.sh
fi

. "/etc/pdebuild-cross/pdebuild-cross.rc"
sudo bash -c "CROSSVERS=$CROSSVERS CROSSARCH=$CROSSARCH pbuilder --execute --save-after-exec --configfile /etc/pdebuild-cross/pdebuild-cross.rc --basetgz $BASETGZ -- $(readlink -f ./fix.sh)"

sudo pbuilder --update --configfile /etc/pdebuild-cross/pdebuild-cross.rc --basetgz "$BASETGZ"
