/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p org.freesmartphone.GSM.Network specs/xml/org.freesmartphone.GSM.Network.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org.freesmartphone.GSM.Network.h"

/*
 * Implementation of interface class OrgFreesmartphoneGSMNetworkInterface
 */

OrgFreesmartphoneGSMNetworkInterface::OrgFreesmartphoneGSMNetworkInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreesmartphoneGSMNetworkInterface::~OrgFreesmartphoneGSMNetworkInterface()
{
}

