/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsopreferencesservice -c QFsoPreferencesService specs/xml/org.freesmartphone.Preferences.Service.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOPREFERENCESSERVICE_H
#define QFSOPREFERENCESSERVICE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.Preferences.Service
 */
class QFSO_EXPORT QFsoPreferencesService: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Preferences.Service"; }

public:
    QFsoPreferencesService(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoPreferencesService();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freesmartphone {
    namespace Preferences {
      typedef ::QFsoPreferencesService Service;
    }
  }
}
#endif
