/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodevicepowersupply -c QFsoDevicePowerSupply specs/xml/org.freesmartphone.Device.PowerSupply.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSODEVICEPOWERSUPPLY_H
#define QFSODEVICEPOWERSUPPLY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.Device.PowerSupply
 */
class QFSO_EXPORT QFsoDevicePowerSupply: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Device.PowerSupply"; }

public:
    QFsoDevicePowerSupply(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoDevicePowerSupply();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> GetCapacity()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("GetCapacity"), argumentList);
    }

    inline QDBusPendingReply<QString> GetPowerStatus()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("GetPowerStatus"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Capacity(int energy);
    void PowerStatus(const QString &status);
};

namespace org {
  namespace freesmartphone {
    namespace Device {
      typedef ::QFsoDevicePowerSupply PowerSupply;
    }
  }
}
#endif
