/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodeviceled -c QFsoDeviceLED specs/xml/org.freesmartphone.Device.LED.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSODEVICELED_H
#define QFSODEVICELED_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.Device.LED
 */
class QFSO_EXPORT QFsoDeviceLED: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Device.LED"; }

public:
    QFsoDeviceLED(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoDeviceLED();

public Q_SLOTS: // METHODS
    inline QFsoDBusPendingReply<> BlinkSeconds(int seconds, int on_duration, int off_duration)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(seconds) << qVariantFromValue(on_duration) << qVariantFromValue(off_duration);
        return fsoAsyncCall(QLatin1String("BlinkSeconds"), argumentList);
    }

    inline QFsoDBusPendingReply<> SetBlinking(int on_duration, int off_duration)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(on_duration) << qVariantFromValue(off_duration);
        return fsoAsyncCall(QLatin1String("SetBlinking"), argumentList);
    }

    inline QFsoDBusPendingReply<> SetBrightness(int brightness)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(brightness);
        return fsoAsyncCall(QLatin1String("SetBrightness"), argumentList);
    }

    inline QFsoDBusPendingReply<> SetNetworking(const QString &interface, const QString &mode)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(interface) << qVariantFromValue(mode);
        return fsoAsyncCall(QLatin1String("SetNetworking"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freesmartphone {
    namespace Device {
      typedef ::QFsoDeviceLED LED;
    }
  }
}
#endif
