/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodeviceorientation -c QFsoDeviceOrientation specs/xml/org.freesmartphone.Device.Orientation.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSODEVICEORIENTATION_H
#define QFSODEVICEORIENTATION_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.Device.Orientation
 */
class QFSO_EXPORT QFsoDeviceOrientation: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Device.Orientation"; }

public:
    QFsoDeviceOrientation(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoDeviceOrientation();

public Q_SLOTS: // METHODS
    inline QFsoDBusPendingReply<QString> GetOrientation()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("GetOrientation"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void OrientationChanged(const QString &orientation);
};

namespace org {
  namespace freesmartphone {
    namespace Device {
      typedef ::QFsoDeviceOrientation Orientation;
    }
  }
}
#endif
