/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsopimdates -c QFsoPIMDates specs/xml/org.freesmartphone.PIM.Dates.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOPIMDATES_H
#define QFSOPIMDATES_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.PIM.Dates
 */
class QFSO_EXPORT QFsoPIMDates: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.PIM.Dates"; }

public:
    QFsoPIMDates(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoPIMDates();

public Q_SLOTS: // METHODS
    inline QFsoDBusPendingReply<QString> Add(const QVariantMap &date_data)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(date_data);
        return fsoAsyncCall(QLatin1String("Add"), argumentList);
    }

    inline QFsoDBusPendingReply<QString> GetSingleEntrySingleField(const QVariantMap &query, const QString &field)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(query) << qVariantFromValue(field);
        return fsoAsyncCall(QLatin1String("GetSingleEntrySingleField"), argumentList);
    }

    inline QFsoDBusPendingReply<QString> Query(const QVariantMap &query)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(query);
        return fsoAsyncCall(QLatin1String("Query"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void NewDate(const QString &date_path);
};

namespace org {
  namespace freesmartphone {
    namespace PIM {
      typedef ::QFsoPIMDates Dates;
    }
  }
}
#endif
