/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsogsmcb -c QFsoGSMCB specs/xml/org.freesmartphone.GSM.CB.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOGSMCB_H
#define QFSOGSMCB_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.GSM.CB
 */
class QFsoGSMCB: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.GSM.CB"; }

public:
    QFsoGSMCB(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoGSMCB();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> GetCellBroadcastSubscriptions()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetCellBroadcastSubscriptions"), argumentList);
    }

    inline QDBusPendingReply<> SetCellBroadcastSubscriptions(const QString &channels)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(channels);
        return asyncCallWithArgumentList(QLatin1String("SetCellBroadcastSubscriptions"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void IncomingCellBroadcast(const QString &text, const QString &language, const QVariantMap &properties);
};

namespace org {
  namespace freesmartphone {
    namespace GSM {
      typedef ::QFsoGSMCB CB;
    }
  }
}
#endif
