/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodevicevibrator -c QFsoDeviceVibrator specs/xml/org.freesmartphone.Device.Vibrator.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSODEVICEVIBRATOR_H_1306329414
#define QFSODEVICEVIBRATOR_H_1306329414

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.Device.Vibrator
 */
class QFsoDeviceVibrator: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Device.Vibrator"; }

public:
    QFsoDeviceVibrator(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoDeviceVibrator();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Stop()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Stop"), argumentList);
    }

    inline QDBusPendingReply<> Vibrate(int duration_ms, int strength_percentage)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(duration_ms) << qVariantFromValue(strength_percentage);
        return asyncCallWithArgumentList(QLatin1String("Vibrate"), argumentList);
    }

    inline QDBusPendingReply<> VibratePattern(int pulses, int on_duration_ms, int off_duration_ms, int strength_percentage)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(pulses) << qVariantFromValue(on_duration_ms) << qVariantFromValue(off_duration_ms) << qVariantFromValue(strength_percentage);
        return asyncCallWithArgumentList(QLatin1String("VibratePattern"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freesmartphone {
    namespace Device {
      typedef ::QFsoDeviceVibrator Vibrator;
    }
  }
}
#endif
