/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsopimcontacts -c QFsoPIMContacts specs/xml/org.freesmartphone.PIM.Contacts.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOPIMCONTACTS_H_1306329414
#define QFSOPIMCONTACTS_H_1306329414

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.PIM.Contacts
 */
class QFsoPIMContacts: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.PIM.Contacts"; }

public:
    QFsoPIMContacts(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoPIMContacts();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Add(const QVariantMap &contact_data)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(contact_data);
        return asyncCallWithArgumentList(QLatin1String("Add"), argumentList);
    }

    inline QDBusPendingReply<QString> GetSingleEntrySingleField(const QVariantMap &query, const QString &field)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(query) << qVariantFromValue(field);
        return asyncCallWithArgumentList(QLatin1String("GetSingleEntrySingleField"), argumentList);
    }

    inline QDBusPendingReply<QString> Query(const QVariantMap &query)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(query);
        return asyncCallWithArgumentList(QLatin1String("Query"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void DeletedContact(const QString &contact_path);
    void NewContact(const QString &contact_path);
    void UpdatedContact(const QString &contact_path, const QVariantMap &contact_data);
};

namespace org {
  namespace freesmartphone {
    namespace PIM {
      typedef ::QFsoPIMContacts Contacts;
    }
  }
}
#endif
