/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsogsmdebug -c QFsoGSMDebug specs/xml/org.freesmartphone.GSM.Debug.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOGSMDEBUG_H
#define QFSOGSMDEBUG_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>
#include "qfsostringmap.h"

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.GSM.Debug
 */
class QFSO_EXPORT QFsoGSMDebug: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.GSM.Debug"; }

public:
    QFsoGSMDebug(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoGSMDebug();

public Q_SLOTS: // METHODS
    inline QFsoDBusPendingReply<QString> DebugCommand(const QString &command, const QString &channel)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(command) << qVariantFromValue(channel);
        return fsoAsyncCall(QLatin1String("DebugCommand"), argumentList);
    }

    inline QFsoDBusPendingReply<> DebugInjectResponse(const QString &response, const QString &channel)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(response) << qVariantFromValue(channel);
        return fsoAsyncCall(QLatin1String("DebugInjectResponse"), argumentList);
    }

    inline QFsoDBusPendingReply<> DebugPing()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("DebugPing"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void DebugStatus(const QFsoStringMap &channels);
};

namespace org {
  namespace freesmartphone {
    namespace GSM {
      typedef ::QFsoGSMDebug Debug;
    }
  }
}
#endif
