/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsonotification -c QFsoNotification specs/xml/org.freesmartphone.Notification.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSONOTIFICATION_H_1306329414
#define QFSONOTIFICATION_H_1306329414

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.Notification
 */
class QFsoNotification: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Notification"; }

public:
    QFsoNotification(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoNotification();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Alarm()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Alarm"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freesmartphone {
    typedef ::QFsoNotification Notification;
  }
}
#endif
