/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsogsmpdp -c QFsoGSMPDP specs/xml/org.freesmartphone.GSM.PDP.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "qfsogsmpdp.h"

/*
 * Implementation of interface class QFsoGSMPDP
 */

QFsoGSMPDP::QFsoGSMPDP(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QFsoDbusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

QFsoGSMPDP::~QFsoGSMPDP()
{
}

