/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodevicerealtimeclock -c QFsoDeviceRealtimeClock specs/xml/org.freesmartphone.Device.RealtimeClock.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSODEVICEREALTIMECLOCK_H_1306329414
#define QFSODEVICEREALTIMECLOCK_H_1306329414

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.Device.RealtimeClock
 */
class QFsoDeviceRealtimeClock: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Device.RealtimeClock"; }

public:
    QFsoDeviceRealtimeClock(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoDeviceRealtimeClock();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> GetCurrentTime()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetCurrentTime"), argumentList);
    }

    inline QDBusPendingReply<int> GetWakeupTime()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetWakeupTime"), argumentList);
    }

    inline QDBusPendingReply<> SetCurrentTime(int time)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(time);
        return asyncCallWithArgumentList(QLatin1String("SetCurrentTime"), argumentList);
    }

    inline QDBusPendingReply<> SetWakeupTime(int time)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(time);
        return asyncCallWithArgumentList(QLatin1String("SetWakeupTime"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Alarm(int time);
    void WakeupTimeChanged(int time);
};

namespace org {
  namespace freesmartphone {
    namespace Device {
      typedef ::QFsoDeviceRealtimeClock RealtimeClock;
    }
  }
}
#endif
