/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsoaudiomanager -c QFsoAudioManager specs/xml/org.freesmartphone.Audio.Manager.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOAUDIOMANAGER_H_1306329414
#define QFSOAUDIOMANAGER_H_1306329414

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.Audio.Manager
 */
class QFsoAudioManager: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Audio.Manager"; }

public:
    QFsoAudioManager(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoAudioManager();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QStringList> GetAvailableDevices(const QString &mode)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(mode);
        return asyncCallWithArgumentList(QLatin1String("GetAvailableDevices"), argumentList);
    }

    inline QDBusPendingReply<QString> GetDevice()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetDevice"), argumentList);
    }

    inline QDBusPendingReply<QString> GetMode()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetMode"), argumentList);
    }

    inline QDBusPendingReply<bool> GetMute(const QString &control)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(control);
        return asyncCallWithArgumentList(QLatin1String("GetMute"), argumentList);
    }

    inline QDBusPendingReply<int> GetVolume(const QString &control)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(control);
        return asyncCallWithArgumentList(QLatin1String("GetVolume"), argumentList);
    }

    inline QDBusPendingReply<QString> PullDevice()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("PullDevice"), argumentList);
    }

    inline QDBusPendingReply<> PushDevice(const QString &device)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(device);
        return asyncCallWithArgumentList(QLatin1String("PushDevice"), argumentList);
    }

    inline QDBusPendingReply<QString> RegisterSession(const QString &stream)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(stream);
        return asyncCallWithArgumentList(QLatin1String("RegisterSession"), argumentList);
    }

    inline QDBusPendingReply<> ReleaseSession(const QString &token)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(token);
        return asyncCallWithArgumentList(QLatin1String("ReleaseSession"), argumentList);
    }

    inline QDBusPendingReply<> SetDevice(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(name);
        return asyncCallWithArgumentList(QLatin1String("SetDevice"), argumentList);
    }

    inline QDBusPendingReply<> SetMode(const QString &mode)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(mode);
        return asyncCallWithArgumentList(QLatin1String("SetMode"), argumentList);
    }

    inline QDBusPendingReply<> SetMute(const QString &control, bool mute)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(control) << qVariantFromValue(mute);
        return asyncCallWithArgumentList(QLatin1String("SetMute"), argumentList);
    }

    inline QDBusPendingReply<> SetVolume(const QString &control, int volume)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(control) << qVariantFromValue(volume);
        return asyncCallWithArgumentList(QLatin1String("SetVolume"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void DeviceChanged(const QString &device);
    void ModeChanged(const QString &mode);
    void MuteChanged(const QString &control, bool mute);
    void VolumeChanged(const QString &control, int volume);
};

namespace org {
  namespace freesmartphone {
    namespace Audio {
      typedef ::QFsoAudioManager Manager;
    }
  }
}
#endif
