/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodevicepowercontrol -c QFsoDevicePowerControl specs/xml/org.freesmartphone.Device.PowerControl.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSODEVICEPOWERCONTROL_H
#define QFSODEVICEPOWERCONTROL_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.Device.PowerControl
 */
class QFSO_EXPORT QFsoDevicePowerControl: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Device.PowerControl"; }

public:
    QFsoDevicePowerControl(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoDevicePowerControl();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<bool> GetPower()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetPower"), argumentList);
    }

    inline QDBusPendingReply<> SetPower(bool on)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(on);
        return asyncCallWithArgumentList(QLatin1String("SetPower"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Power(bool on);
};

namespace org {
  namespace freesmartphone {
    namespace Device {
      typedef ::QFsoDevicePowerControl PowerControl;
    }
  }
}
#endif
