/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsophonecall -c QFsoPhoneCall specs/xml/org.freesmartphone.Phone.Call.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOPHONECALL_H_1306329414
#define QFSOPHONECALL_H_1306329414

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.Phone.Call
 */
class QFsoPhoneCall: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.Phone.Call"; }

public:
    QFsoPhoneCall(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoPhoneCall();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Activate()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Activate"), argumentList);
    }

    inline QDBusPendingReply<QString> GetPeer()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetPeer"), argumentList);
    }

    inline QDBusPendingReply<QString> GetStatus()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetStatus"), argumentList);
    }

    inline QDBusPendingReply<QString> Initiate()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Initiate"), argumentList);
    }

    inline QDBusPendingReply<QString> Release()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Release"), argumentList);
    }

    inline QDBusPendingReply<> Remove()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Remove"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Activated();
    void Incoming();
    void Outgoing();
    void Released();
};

namespace org {
  namespace freesmartphone {
    namespace Phone {
      typedef ::QFsoPhoneCall Call;
    }
  }
}
#endif
