/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsodeviceaudio -c QFsoDeviceAudio specs/xml/org.freesmartphone.Device.Audio.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "qfsodeviceaudio.h"

/*
 * Implementation of interface class QFsoDeviceAudio
 */

QFsoDeviceAudio::QFsoDeviceAudio(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QFsoDbusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

QFsoDeviceAudio::~QFsoDeviceAudio()
{
}

