/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsopimtasks -c QFsoPIMTasks specs/xml/org.freesmartphone.PIM.Tasks.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOPIMTASKS_H
#define QFSOPIMTASKS_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freesmartphone.PIM.Tasks
 */
class QFsoPIMTasks: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.PIM.Tasks"; }

public:
    QFsoPIMTasks(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoPIMTasks();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Add(const QVariantMap &task_data)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(task_data);
        return asyncCallWithArgumentList(QLatin1String("Add"), argumentList);
    }

    inline QDBusPendingReply<QString> GetSingleTaskSingleField(const QVariantMap &query, const QString &field)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(query) << qVariantFromValue(field);
        return asyncCallWithArgumentList(QLatin1String("GetSingleTaskSingleField"), argumentList);
    }

    inline QDBusPendingReply<QString> Query(const QVariantMap &query)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(query);
        return asyncCallWithArgumentList(QLatin1String("Query"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void NewTask(const QString &task_path);
    void UnfinishedTasks(int amount);
};

namespace org {
  namespace freesmartphone {
    namespace PIM {
      typedef ::QFsoPIMTasks Tasks;
    }
  }
}
#endif
