/*
 * This file was generated by qfsodbusxml2cpp version 0.7
 * Command line was: qfsodbusxml2cpp -p qfsopimnote -c QFsoPIMNote specs/xml/org.freesmartphone.PIM.Note.xml
 *
 * qfsodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QFSOPIMNOTE_H
#define QFSOPIMNOTE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qfsodbusabstractinterface.h>

#if defined(QFSO_LIBRARY)
    #define QFSO_EXPORT Q_DECL_EXPORT
#else
    #define QFSO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.freesmartphone.PIM.Note
 */
class QFSO_EXPORT QFsoPIMNote: public QFsoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freesmartphone.PIM.Note"; }

public:
    QFsoPIMNote(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~QFsoPIMNote();

public Q_SLOTS: // METHODS
    inline QFsoDBusPendingReply<> Delete()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("Delete"), argumentList);
    }

    inline QFsoDBusPendingReply<QVariantMap> GetContent()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("GetContent"), argumentList);
    }

    inline QFsoDBusPendingReply<QVariantMap> GetMultipleFields(const QString &field_list)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(field_list);
        return fsoAsyncCall(QLatin1String("GetMultipleFields"), argumentList);
    }

    inline QFsoDBusPendingReply<QStringList> GetUsedBackends()
    {
        QList<QVariant> argumentList;
        return fsoAsyncCall(QLatin1String("GetUsedBackends"), argumentList);
    }

    inline QFsoDBusPendingReply<> Update(const QVariantMap &note_data)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(note_data);
        return fsoAsyncCall(QLatin1String("Update"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void NoteDeleted();
    void NoteUpdated(const QVariantMap &data);
};

namespace org {
  namespace freesmartphone {
    namespace PIM {
      typedef ::QFsoPIMNote Note;
    }
  }
}
#endif
