/*
 * This file was generated by qofonodbusxml2cpp version 0.7
 * Command line was: qofonodbusxml2cpp -p ofonosupplementaryservices ofono.xml org.ofono.SupplementaryServices
 *
 * qofonodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOSUPPLEMENTARYSERVICES_H
#define OFONOSUPPLEMENTARYSERVICES_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qofonodbusabstractinterface.h>

#if defined(QOFONO_LIBRARY)
    #define QOFONO_EXPORT Q_DECL_EXPORT
#else
    #define QOFONO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.ofono.SupplementaryServices
 */
class QOFONO_EXPORT OrgOfonoSupplementaryServicesInterface: public QOFonoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.SupplementaryServices"; }

public:
    OrgOfonoSupplementaryServicesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgOfonoSupplementaryServicesInterface();

public Q_SLOTS: // METHODS
    inline QOFonoDBusPendingReply<> Cancel()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("Cancel"), argumentList);
    }

    inline QOFonoDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("GetProperties"), argumentList);
    }

    inline QOFonoDBusPendingReply<QString, QDBusVariant> Initiate(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return ofonoAsyncCall(QLatin1String("Initiate"), argumentList);
    }
    inline QDBusReply<QString> Initiate(const QString &in0, QDBusVariant &out1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        QDBusMessage reply = callWithArgumentList(QDBus::Block, QLatin1String("Initiate"), argumentList);
        if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().count() == 2) {
            out1 = qdbus_cast<QDBusVariant>(reply.arguments().at(1));
        }
        return reply;
    }

    inline QOFonoDBusPendingReply<QString> Respond(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return ofonoAsyncCall(QLatin1String("Respond"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void NotificationReceived(const QString &in0);
    void PropertyChanged(const QString &in0, const QDBusVariant &in1);
    void RequestReceived(const QString &in0);
};

namespace org {
  namespace ofono {
    typedef ::OrgOfonoSupplementaryServicesInterface SupplementaryServices;
  }
}
#endif
