/*
 * This file was generated by qofonodbusxml2cpp version 0.7
 * Command line was: qofonodbusxml2cpp -p ofonophonebook ofono.xml org.ofono.Phonebook
 *
 * qofonodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOPHONEBOOK_H
#define OFONOPHONEBOOK_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qofonodbusabstractinterface.h>

#if defined(QOFONO_LIBRARY)
    #define QOFONO_EXPORT Q_DECL_EXPORT
#else
    #define QOFONO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.ofono.Phonebook
 */
class QOFONO_EXPORT OrgOfonoPhonebookInterface: public QOFonoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.Phonebook"; }

public:
    OrgOfonoPhonebookInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgOfonoPhonebookInterface();

public Q_SLOTS: // METHODS
    inline QOFonoDBusPendingReply<QString> Import()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("Import"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace ofono {
    typedef ::OrgOfonoPhonebookInterface Phonebook;
  }
}
#endif
