/*
 * This file was generated by qofonodbusxml2cpp version 0.7
 * Command line was: qofonodbusxml2cpp -p qofonomanager ofono.xml org.ofono.Manager
 *
 * qofonodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QOFONOMANAGER_H
#define QOFONOMANAGER_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qofonodbusabstractinterface.h>
#include "qofonoobjectlist.h"

#if defined(QOFONO_LIBRARY)
    #define QOFONO_EXPORT Q_DECL_EXPORT
#else
    #define QOFONO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.ofono.Manager
 */
class QOFONO_EXPORT OrgOfonoManagerInterface: public QOFonoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.Manager"; }

public:
    OrgOfonoManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgOfonoManagerInterface();

public Q_SLOTS: // METHODS
    inline QOFonoDBusPendingReply<QOFonoObjectList> GetModems()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("GetModems"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void ModemAdded(const QDBusObjectPath &in0, const QVariantMap &in1);
    void ModemRemoved(const QDBusObjectPath &in0);
};

namespace org {
  namespace ofono {
    typedef ::OrgOfonoManagerInterface Manager;
  }
}
#endif
