/*
 * This file was generated by qofonodbusxml2cpp version 0.7
 * Command line was: qofonodbusxml2cpp -p qofonosimmanager ofono.xml org.ofono.SimManager
 *
 * qofonodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QOFONOSIMMANAGER_H
#define QOFONOSIMMANAGER_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qofonodbusabstractinterface.h>

#if defined(QOFONO_LIBRARY)
    #define QOFONO_EXPORT Q_DECL_EXPORT
#else
    #define QOFONO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.ofono.SimManager
 */
class QOFONO_EXPORT OrgOfonoSimManagerInterface: public QOFonoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.SimManager"; }

public:
    OrgOfonoSimManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgOfonoSimManagerInterface();

public Q_SLOTS: // METHODS
    inline QOFonoDBusPendingReply<> ChangePin(const QString &in0, const QString &in1, const QString &in2)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1) << qVariantFromValue(in2);
        return ofonoAsyncCall(QLatin1String("ChangePin"), argumentList);
    }

    inline QOFonoDBusPendingReply<> EnterPin(const QString &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return ofonoAsyncCall(QLatin1String("EnterPin"), argumentList);
    }

    inline QOFonoDBusPendingReply<QByteArray> GetIcon(uchar in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return ofonoAsyncCall(QLatin1String("GetIcon"), argumentList);
    }

    inline QOFonoDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("GetProperties"), argumentList);
    }

    inline QOFonoDBusPendingReply<> LockPin(const QString &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return ofonoAsyncCall(QLatin1String("LockPin"), argumentList);
    }

    inline QOFonoDBusPendingReply<> ResetPin(const QString &in0, const QString &in1, const QString &in2)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1) << qVariantFromValue(in2);
        return ofonoAsyncCall(QLatin1String("ResetPin"), argumentList);
    }

    inline QOFonoDBusPendingReply<> SetProperty(const QString &in0, const QDBusVariant &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return ofonoAsyncCall(QLatin1String("SetProperty"), argumentList);
    }

    inline QOFonoDBusPendingReply<> UnlockPin(const QString &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return ofonoAsyncCall(QLatin1String("UnlockPin"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void PropertyChanged(const QString &in0, const QDBusVariant &in1);
};

namespace org {
  namespace ofono {
    typedef ::OrgOfonoSimManagerInterface SimManager;
  }
}
#endif
