/*
 * This file was generated by qofonodbusxml2cpp version 0.7
 * Command line was: qofonodbusxml2cpp -p qofonoconnectionmanager ofono.xml org.ofono.ConnectionManager
 *
 * qofonodbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QOFONOCONNECTIONMANAGER_H
#define QOFONOCONNECTIONMANAGER_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <qofonodbusabstractinterface.h>
#include "qofonoobjectlist.h"

#if defined(QOFONO_LIBRARY)
    #define QOFONO_EXPORT Q_DECL_EXPORT
#else
    #define QOFONO_EXPORT Q_DECL_IMPORT
#endif

/*
 * Proxy class for interface org.ofono.ConnectionManager
 */
class QOFONO_EXPORT OrgOfonoConnectionManagerInterface: public QOFonoDbusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.ConnectionManager"; }

public:
    OrgOfonoConnectionManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgOfonoConnectionManagerInterface();

public Q_SLOTS: // METHODS
    inline QOFonoDBusPendingReply<QDBusObjectPath> AddContext(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return ofonoAsyncCall(QLatin1String("AddContext"), argumentList);
    }

    inline QOFonoDBusPendingReply<> DeactivateAll()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("DeactivateAll"), argumentList);
    }

    inline QOFonoDBusPendingReply<QOFonoObjectList> GetContexts()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("GetContexts"), argumentList);
    }

    inline QOFonoDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return ofonoAsyncCall(QLatin1String("GetProperties"), argumentList);
    }

    inline QOFonoDBusPendingReply<> RemoveContext(const QDBusObjectPath &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return ofonoAsyncCall(QLatin1String("RemoveContext"), argumentList);
    }

    inline QOFonoDBusPendingReply<> SetProperty(const QString &in0, const QDBusVariant &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return ofonoAsyncCall(QLatin1String("SetProperty"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void ContextAdded(const QDBusObjectPath &in0, const QVariantMap &in1);
    void ContextRemoved(const QDBusObjectPath &in0);
    void PropertyChanged(const QString &in0, const QDBusVariant &in1);
};

namespace org {
  namespace ofono {
    typedef ::OrgOfonoConnectionManagerInterface ConnectionManager;
  }
}
#endif
