#!/bin/sh

echo "Running environment script for device neo with PKG_CONFIG_LIBDIR=$PKG_CONFIG_LIBDIR"

# Guess PKG_CONFIG_LIBDIR if not already exported (e.g. by dpkg-builpackage).
# It should point to directory where .pc files are see:
# http://radekp.github.com/qtmoko/api/buildsystem/over-device-profiles-1.html#pkg-config

# Cross compiling
PKG_CONFIG_LIBDIR=${PKG_CONFIG_LIBDIR:-/usr/arm-linux-gnueabi/lib/pkgconfig}

# Native toolchain on squeeze/armel
if [ ! -d "$PKG_CONFIG_LIBDIR" ]; then
    PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig
fi

if [ -d "$PKG_CONFIG_LIBDIR" ]; then
    echo "Variable PKG_CONFIG_LIBDIR is now set to: $PKG_CONFIG_LIBDIR"
else
    echo "Warning: PKG_CONFIG_LIBDIR directory $PKG_CONFIG_LIBDIR does not exist!!"
fi

export PKG_CONFIG_LIBDIR
