Document: qtmoko
Title: Debian qtmoko Manual
Author: <insert document author here>
Abstract: This manual describes what qtmoko is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtmoko/qtmoko.sgml.gz

Format: postscript
Files: /usr/share/doc/qtmoko/qtmoko.ps.gz

Format: text
Files: /usr/share/doc/qtmoko/qtmoko.text.gz

Format: HTML
Index: /usr/share/doc/qtmoko/html/index.html
Files: /usr/share/doc/qtmoko/html/*.html
